// Code generated by MockGen. DO NOT EDIT.
// Source: example/clients/clients.go
//
// Generated by this command:
//
//	mockgen -source example/clients/clients.go -destination example/clients/mocks.go -package clients
//

// Package clients is a generated GoMock package.
package clients

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockDistributedCache is a mock of DistributedCache interface.
type MockDistributedCache struct {
	ctrl     *gomock.Controller
	recorder *MockDistributedCacheMockRecorder
	isgomock struct{}
}

// MockDistributedCacheMockRecorder is the mock recorder for MockDistributedCache.
type MockDistributedCacheMockRecorder struct {
	mock *MockDistributedCache
}

// NewMockDistributedCache creates a new mock instance.
func NewMockDistributedCache(ctrl *gomock.Controller) *MockDistributedCache {
	mock := &MockDistributedCache{ctrl: ctrl}
	mock.recorder = &MockDistributedCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDistributedCache) EXPECT() *MockDistributedCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockDistributedCache) Get(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDistributedCacheMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDistributedCache)(nil).Get), ctx, key)
}

// Remove mocks base method.
func (m *MockDistributedCache) Remove(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockDistributedCacheMockRecorder) Remove(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockDistributedCache)(nil).Remove), ctx, key)
}

// Set mocks base method.
func (m *MockDistributedCache) Set(ctx context.Context, key, value string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockDistributedCacheMockRecorder) Set(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockDistributedCache)(nil).Set), ctx, key, value, ttl)
}
