// Code generated by MockGen. DO NOT EDIT.
// Source: container/mokkitgomock/internal/shop/shop.go
//
// Generated by this command:
//
//	mockgen -source container/mokkitgomock/internal/shop/shop.go -destination container/mokkitgomock/internal/shop/mocks.go -package shop
//

// Package shop is a generated GoMock package.
package shop

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// ByID mocks base method.
func (m *MockUserRepository) ByID(ctx context.Context, id string) (User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByID", ctx, id)
	ret0, _ := ret[0].(User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByID indicates an expected call of ByID.
func (mr *MockUserRepositoryMockRecorder) ByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByID", reflect.TypeOf((*MockUserRepository)(nil).ByID), ctx, id)
}

// MockRateRepository is a mock of RateRepository interface.
type MockRateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRateRepositoryMockRecorder
	isgomock struct{}
}

// MockRateRepositoryMockRecorder is the mock recorder for MockRateRepository.
type MockRateRepositoryMockRecorder struct {
	mock *MockRateRepository
}

// NewMockRateRepository creates a new mock instance.
func NewMockRateRepository(ctrl *gomock.Controller) *MockRateRepository {
	mock := &MockRateRepository{ctrl: ctrl}
	mock.recorder = &MockRateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateRepository) EXPECT() *MockRateRepositoryMockRecorder {
	return m.recorder
}

// RateFor mocks base method.
func (m *MockRateRepository) RateFor(ctx context.Context, status string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RateFor", ctx, status)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RateFor indicates an expected call of RateFor.
func (mr *MockRateRepositoryMockRecorder) RateFor(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RateFor", reflect.TypeOf((*MockRateRepository)(nil).RateFor), ctx, status)
}

// MockAudit is a mock of Audit interface.
type MockAudit struct {
	ctrl     *gomock.Controller
	recorder *MockAuditMockRecorder
	isgomock struct{}
}

// MockAuditMockRecorder is the mock recorder for MockAudit.
type MockAuditMockRecorder struct {
	mock *MockAudit
}

// NewMockAudit creates a new mock instance.
func NewMockAudit(ctrl *gomock.Controller) *MockAudit {
	mock := &MockAudit{ctrl: ctrl}
	mock.recorder = &MockAuditMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAudit) EXPECT() *MockAuditMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockAudit) Record(ctx context.Context, userID string, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Record", ctx, userID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Record indicates an expected call of Record.
func (mr *MockAuditMockRecorder) Record(ctx, userID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockAudit)(nil).Record), ctx, userID, amount)
}
