// Code generated by http://github.com/gojuno/minimock (v3.4.0). DO NOT EDIT.

package shop

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// AuditMock implements Audit
type AuditMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcRecord          func(ctx context.Context, userID string, amount float64) (err error)
	funcRecordOrigin    string
	inspectFuncRecord   func(ctx context.Context, userID string, amount float64)
	afterRecordCounter  uint64
	beforeRecordCounter uint64
	RecordMock          mAuditMockRecord
}

// NewAuditMock returns a mock for Audit
func NewAuditMock(t minimock.Tester) *AuditMock {
	m := &AuditMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.RecordMock = mAuditMockRecord{mock: m}
	m.RecordMock.callArgs = []*AuditMockRecordParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAuditMockRecord struct {
	optional           bool
	mock               *AuditMock
	defaultExpectation *AuditMockRecordExpectation
	expectations       []*AuditMockRecordExpectation

	callArgs []*AuditMockRecordParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuditMockRecordExpectation specifies expectation struct of the Audit.Record
type AuditMockRecordExpectation struct {
	mock               *AuditMock
	params             *AuditMockRecordParams
	paramPtrs          *AuditMockRecordParamPtrs
	expectationOrigins AuditMockRecordExpectationOrigins
	results            *AuditMockRecordResults
	returnOrigin       string
	Counter            uint64
}

// AuditMockRecordParams contains parameters of the Audit.Record
type AuditMockRecordParams struct {
	ctx    context.Context
	userID string
	amount float64
}

// AuditMockRecordParamPtrs contains pointers to parameters of the Audit.Record
type AuditMockRecordParamPtrs struct {
	ctx    *context.Context
	userID *string
	amount *float64
}

// AuditMockRecordResults contains results of the Audit.Record
type AuditMockRecordResults struct {
	err error
}

// AuditMockRecordOrigins contains origins of expectations of the Audit.Record
type AuditMockRecordExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
	originAmount string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRecord *mAuditMockRecord) Optional() *mAuditMockRecord {
	mmRecord.optional = true
	return mmRecord
}

// Expect sets up expected params for Audit.Record
func (mmRecord *mAuditMockRecord) Expect(ctx context.Context, userID string, amount float64) *mAuditMockRecord {
	if mmRecord.mock.funcRecord != nil {
		mmRecord.mock.t.Fatalf("AuditMock.Record mock is already set by Set")
	}

	if mmRecord.defaultExpectation == nil {
		mmRecord.defaultExpectation = &AuditMockRecordExpectation{}
	}

	if mmRecord.defaultExpectation.paramPtrs != nil {
		mmRecord.mock.t.Fatalf("AuditMock.Record mock is already set by ExpectParams functions")
	}

	mmRecord.defaultExpectation.params = &AuditMockRecordParams{ctx, userID, amount}
	mmRecord.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRecord.expectations {
		if minimock.Equal(e.params, mmRecord.defaultExpectation.params) {
			mmRecord.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRecord.defaultExpectation.params)
		}
	}

	return mmRecord
}

// ExpectCtxParam1 sets up expected param ctx for Audit.Record
func (mmRecord *mAuditMockRecord) ExpectCtxParam1(ctx context.Context) *mAuditMockRecord {
	if mmRecord.mock.funcRecord != nil {
		mmRecord.mock.t.Fatalf("AuditMock.Record mock is already set by Set")
	}

	if mmRecord.defaultExpectation == nil {
		mmRecord.defaultExpectation = &AuditMockRecordExpectation{}
	}

	if mmRecord.defaultExpectation.params != nil {
		mmRecord.mock.t.Fatalf("AuditMock.Record mock is already set by Expect")
	}

	if mmRecord.defaultExpectation.paramPtrs == nil {
		mmRecord.defaultExpectation.paramPtrs = &AuditMockRecordParamPtrs{}
	}
	mmRecord.defaultExpectation.paramPtrs.ctx = &ctx
	mmRecord.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmRecord
}

// ExpectUserIDParam2 sets up expected param userID for Audit.Record
func (mmRecord *mAuditMockRecord) ExpectUserIDParam2(userID string) *mAuditMockRecord {
	if mmRecord.mock.funcRecord != nil {
		mmRecord.mock.t.Fatalf("AuditMock.Record mock is already set by Set")
	}

	if mmRecord.defaultExpectation == nil {
		mmRecord.defaultExpectation = &AuditMockRecordExpectation{}
	}

	if mmRecord.defaultExpectation.params != nil {
		mmRecord.mock.t.Fatalf("AuditMock.Record mock is already set by Expect")
	}

	if mmRecord.defaultExpectation.paramPtrs == nil {
		mmRecord.defaultExpectation.paramPtrs = &AuditMockRecordParamPtrs{}
	}
	mmRecord.defaultExpectation.paramPtrs.userID = &userID
	mmRecord.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmRecord
}

// ExpectAmountParam3 sets up expected param amount for Audit.Record
func (mmRecord *mAuditMockRecord) ExpectAmountParam3(amount float64) *mAuditMockRecord {
	if mmRecord.mock.funcRecord != nil {
		mmRecord.mock.t.Fatalf("AuditMock.Record mock is already set by Set")
	}

	if mmRecord.defaultExpectation == nil {
		mmRecord.defaultExpectation = &AuditMockRecordExpectation{}
	}

	if mmRecord.defaultExpectation.params != nil {
		mmRecord.mock.t.Fatalf("AuditMock.Record mock is already set by Expect")
	}

	if mmRecord.defaultExpectation.paramPtrs == nil {
		mmRecord.defaultExpectation.paramPtrs = &AuditMockRecordParamPtrs{}
	}
	mmRecord.defaultExpectation.paramPtrs.amount = &amount
	mmRecord.defaultExpectation.expectationOrigins.originAmount = minimock.CallerInfo(1)

	return mmRecord
}

// Inspect accepts an inspector function that has same arguments as the Audit.Record
func (mmRecord *mAuditMockRecord) Inspect(f func(ctx context.Context, userID string, amount float64)) *mAuditMockRecord {
	if mmRecord.mock.inspectFuncRecord != nil {
		mmRecord.mock.t.Fatalf("Inspect function is already set for AuditMock.Record")
	}

	mmRecord.mock.inspectFuncRecord = f

	return mmRecord
}

// Return sets up results that will be returned by Audit.Record
func (mmRecord *mAuditMockRecord) Return(err error) *AuditMock {
	if mmRecord.mock.funcRecord != nil {
		mmRecord.mock.t.Fatalf("AuditMock.Record mock is already set by Set")
	}

	if mmRecord.defaultExpectation == nil {
		mmRecord.defaultExpectation = &AuditMockRecordExpectation{mock: mmRecord.mock}
	}
	mmRecord.defaultExpectation.results = &AuditMockRecordResults{err}
	mmRecord.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRecord.mock
}

// Set uses given function f to mock the Audit.Record method
func (mmRecord *mAuditMockRecord) Set(f func(ctx context.Context, userID string, amount float64) (err error)) *AuditMock {
	if mmRecord.defaultExpectation != nil {
		mmRecord.mock.t.Fatalf("Default expectation is already set for the Audit.Record method")
	}

	if len(mmRecord.expectations) > 0 {
		mmRecord.mock.t.Fatalf("Some expectations are already set for the Audit.Record method")
	}

	mmRecord.mock.funcRecord = f
	mmRecord.mock.funcRecordOrigin = minimock.CallerInfo(1)
	return mmRecord.mock
}

// When sets expectation for the Audit.Record which will trigger the result defined by the following
// Then helper
func (mmRecord *mAuditMockRecord) When(ctx context.Context, userID string, amount float64) *AuditMockRecordExpectation {
	if mmRecord.mock.funcRecord != nil {
		mmRecord.mock.t.Fatalf("AuditMock.Record mock is already set by Set")
	}

	expectation := &AuditMockRecordExpectation{
		mock:               mmRecord.mock,
		params:             &AuditMockRecordParams{ctx, userID, amount},
		expectationOrigins: AuditMockRecordExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRecord.expectations = append(mmRecord.expectations, expectation)
	return expectation
}

// Then sets up Audit.Record return parameters for the expectation previously defined by the When method
func (e *AuditMockRecordExpectation) Then(err error) *AuditMock {
	e.results = &AuditMockRecordResults{err}
	return e.mock
}

// Times sets number of times Audit.Record should be invoked
func (mmRecord *mAuditMockRecord) Times(n uint64) *mAuditMockRecord {
	if n == 0 {
		mmRecord.mock.t.Fatalf("Times of AuditMock.Record mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRecord.expectedInvocations, n)
	mmRecord.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRecord
}

func (mmRecord *mAuditMockRecord) invocationsDone() bool {
	if len(mmRecord.expectations) == 0 && mmRecord.defaultExpectation == nil && mmRecord.mock.funcRecord == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRecord.mock.afterRecordCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRecord.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Record implements Audit
func (mmRecord *AuditMock) Record(ctx context.Context, userID string, amount float64) (err error) {
	mm_atomic.AddUint64(&mmRecord.beforeRecordCounter, 1)
	defer mm_atomic.AddUint64(&mmRecord.afterRecordCounter, 1)

	mmRecord.t.Helper()

	if mmRecord.inspectFuncRecord != nil {
		mmRecord.inspectFuncRecord(ctx, userID, amount)
	}

	mm_params := AuditMockRecordParams{ctx, userID, amount}

	// Record call args
	mmRecord.RecordMock.mutex.Lock()
	mmRecord.RecordMock.callArgs = append(mmRecord.RecordMock.callArgs, &mm_params)
	mmRecord.RecordMock.mutex.Unlock()

	for _, e := range mmRecord.RecordMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmRecord.RecordMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRecord.RecordMock.defaultExpectation.Counter, 1)
		mm_want := mmRecord.RecordMock.defaultExpectation.params
		mm_want_ptrs := mmRecord.RecordMock.defaultExpectation.paramPtrs

		mm_got := AuditMockRecordParams{ctx, userID, amount}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmRecord.t.Errorf("AuditMock.Record got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRecord.RecordMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmRecord.t.Errorf("AuditMock.Record got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRecord.RecordMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.amount != nil && !minimock.Equal(*mm_want_ptrs.amount, mm_got.amount) {
				mmRecord.t.Errorf("AuditMock.Record got unexpected parameter amount, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRecord.RecordMock.defaultExpectation.expectationOrigins.originAmount, *mm_want_ptrs.amount, mm_got.amount, minimock.Diff(*mm_want_ptrs.amount, mm_got.amount))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRecord.t.Errorf("AuditMock.Record got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRecord.RecordMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRecord.RecordMock.defaultExpectation.results
		if mm_results == nil {
			mmRecord.t.Fatal("No results are set for the AuditMock.Record")
		}
		return (*mm_results).err
	}
	if mmRecord.funcRecord != nil {
		return mmRecord.funcRecord(ctx, userID, amount)
	}
	mmRecord.t.Fatalf("Unexpected call to AuditMock.Record. %v %v %v", ctx, userID, amount)
	return
}

// RecordAfterCounter returns a count of finished AuditMock.Record invocations
func (mmRecord *AuditMock) RecordAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRecord.afterRecordCounter)
}

// RecordBeforeCounter returns a count of AuditMock.Record invocations
func (mmRecord *AuditMock) RecordBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRecord.beforeRecordCounter)
}

// Calls returns a list of arguments used in each call to AuditMock.Record.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRecord *mAuditMockRecord) Calls() []*AuditMockRecordParams {
	mmRecord.mutex.RLock()

	argCopy := make([]*AuditMockRecordParams, len(mmRecord.callArgs))
	copy(argCopy, mmRecord.callArgs)

	mmRecord.mutex.RUnlock()

	return argCopy
}

// MinimockRecordDone returns true if the count of the Record invocations corresponds
// the number of defined expectations
func (m *AuditMock) MinimockRecordDone() bool {
	if m.RecordMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RecordMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RecordMock.invocationsDone()
}

// MinimockRecordInspect logs each unmet expectation
func (m *AuditMock) MinimockRecordInspect() {
	for _, e := range m.RecordMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuditMock.Record at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRecordCounter := mm_atomic.LoadUint64(&m.afterRecordCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RecordMock.defaultExpectation != nil && afterRecordCounter < 1 {
		if m.RecordMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuditMock.Record at\n%s", m.RecordMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuditMock.Record at\n%s with params: %#v", m.RecordMock.defaultExpectation.expectationOrigins.origin, *m.RecordMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRecord != nil && afterRecordCounter < 1 {
		m.t.Errorf("Expected call to AuditMock.Record at\n%s", m.funcRecordOrigin)
	}

	if !m.RecordMock.invocationsDone() && afterRecordCounter > 0 {
		m.t.Errorf("Expected %d calls to AuditMock.Record at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RecordMock.expectedInvocations), m.RecordMock.expectedInvocationsOrigin, afterRecordCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AuditMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockRecordInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AuditMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AuditMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockRecordDone()
}
