// Code generated by http://github.com/gojuno/minimock (v3.4.0). DO NOT EDIT.

package shop

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// RateRepositoryMock implements RateRepository
type RateRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcRateFor          func(ctx context.Context, status string) (f1 float64, err error)
	funcRateForOrigin    string
	inspectFuncRateFor   func(ctx context.Context, status string)
	afterRateForCounter  uint64
	beforeRateForCounter uint64
	RateForMock          mRateRepositoryMockRateFor
}

// NewRateRepositoryMock returns a mock for RateRepository
func NewRateRepositoryMock(t minimock.Tester) *RateRepositoryMock {
	m := &RateRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.RateForMock = mRateRepositoryMockRateFor{mock: m}
	m.RateForMock.callArgs = []*RateRepositoryMockRateForParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRateRepositoryMockRateFor struct {
	optional           bool
	mock               *RateRepositoryMock
	defaultExpectation *RateRepositoryMockRateForExpectation
	expectations       []*RateRepositoryMockRateForExpectation

	callArgs []*RateRepositoryMockRateForParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RateRepositoryMockRateForExpectation specifies expectation struct of the RateRepository.RateFor
type RateRepositoryMockRateForExpectation struct {
	mock               *RateRepositoryMock
	params             *RateRepositoryMockRateForParams
	paramPtrs          *RateRepositoryMockRateForParamPtrs
	expectationOrigins RateRepositoryMockRateForExpectationOrigins
	results            *RateRepositoryMockRateForResults
	returnOrigin       string
	Counter            uint64
}

// RateRepositoryMockRateForParams contains parameters of the RateRepository.RateFor
type RateRepositoryMockRateForParams struct {
	ctx    context.Context
	status string
}

// RateRepositoryMockRateForParamPtrs contains pointers to parameters of the RateRepository.RateFor
type RateRepositoryMockRateForParamPtrs struct {
	ctx    *context.Context
	status *string
}

// RateRepositoryMockRateForResults contains results of the RateRepository.RateFor
type RateRepositoryMockRateForResults struct {
	f1  float64
	err error
}

// RateRepositoryMockRateForOrigins contains origins of expectations of the RateRepository.RateFor
type RateRepositoryMockRateForExpectationOrigins struct {
	origin       string
	originCtx    string
	originStatus string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRateFor *mRateRepositoryMockRateFor) Optional() *mRateRepositoryMockRateFor {
	mmRateFor.optional = true
	return mmRateFor
}

// Expect sets up expected params for RateRepository.RateFor
func (mmRateFor *mRateRepositoryMockRateFor) Expect(ctx context.Context, status string) *mRateRepositoryMockRateFor {
	if mmRateFor.mock.funcRateFor != nil {
		mmRateFor.mock.t.Fatalf("RateRepositoryMock.RateFor mock is already set by Set")
	}

	if mmRateFor.defaultExpectation == nil {
		mmRateFor.defaultExpectation = &RateRepositoryMockRateForExpectation{}
	}

	if mmRateFor.defaultExpectation.paramPtrs != nil {
		mmRateFor.mock.t.Fatalf("RateRepositoryMock.RateFor mock is already set by ExpectParams functions")
	}

	mmRateFor.defaultExpectation.params = &RateRepositoryMockRateForParams{ctx, status}
	mmRateFor.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRateFor.expectations {
		if minimock.Equal(e.params, mmRateFor.defaultExpectation.params) {
			mmRateFor.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRateFor.defaultExpectation.params)
		}
	}

	return mmRateFor
}

// ExpectCtxParam1 sets up expected param ctx for RateRepository.RateFor
func (mmRateFor *mRateRepositoryMockRateFor) ExpectCtxParam1(ctx context.Context) *mRateRepositoryMockRateFor {
	if mmRateFor.mock.funcRateFor != nil {
		mmRateFor.mock.t.Fatalf("RateRepositoryMock.RateFor mock is already set by Set")
	}

	if mmRateFor.defaultExpectation == nil {
		mmRateFor.defaultExpectation = &RateRepositoryMockRateForExpectation{}
	}

	if mmRateFor.defaultExpectation.params != nil {
		mmRateFor.mock.t.Fatalf("RateRepositoryMock.RateFor mock is already set by Expect")
	}

	if mmRateFor.defaultExpectation.paramPtrs == nil {
		mmRateFor.defaultExpectation.paramPtrs = &RateRepositoryMockRateForParamPtrs{}
	}
	mmRateFor.defaultExpectation.paramPtrs.ctx = &ctx
	mmRateFor.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmRateFor
}

// ExpectStatusParam2 sets up expected param status for RateRepository.RateFor
func (mmRateFor *mRateRepositoryMockRateFor) ExpectStatusParam2(status string) *mRateRepositoryMockRateFor {
	if mmRateFor.mock.funcRateFor != nil {
		mmRateFor.mock.t.Fatalf("RateRepositoryMock.RateFor mock is already set by Set")
	}

	if mmRateFor.defaultExpectation == nil {
		mmRateFor.defaultExpectation = &RateRepositoryMockRateForExpectation{}
	}

	if mmRateFor.defaultExpectation.params != nil {
		mmRateFor.mock.t.Fatalf("RateRepositoryMock.RateFor mock is already set by Expect")
	}

	if mmRateFor.defaultExpectation.paramPtrs == nil {
		mmRateFor.defaultExpectation.paramPtrs = &RateRepositoryMockRateForParamPtrs{}
	}
	mmRateFor.defaultExpectation.paramPtrs.status = &status
	mmRateFor.defaultExpectation.expectationOrigins.originStatus = minimock.CallerInfo(1)

	return mmRateFor
}

// Inspect accepts an inspector function that has same arguments as the RateRepository.RateFor
func (mmRateFor *mRateRepositoryMockRateFor) Inspect(f func(ctx context.Context, status string)) *mRateRepositoryMockRateFor {
	if mmRateFor.mock.inspectFuncRateFor != nil {
		mmRateFor.mock.t.Fatalf("Inspect function is already set for RateRepositoryMock.RateFor")
	}

	mmRateFor.mock.inspectFuncRateFor = f

	return mmRateFor
}

// Return sets up results that will be returned by RateRepository.RateFor
func (mmRateFor *mRateRepositoryMockRateFor) Return(f1 float64, err error) *RateRepositoryMock {
	if mmRateFor.mock.funcRateFor != nil {
		mmRateFor.mock.t.Fatalf("RateRepositoryMock.RateFor mock is already set by Set")
	}

	if mmRateFor.defaultExpectation == nil {
		mmRateFor.defaultExpectation = &RateRepositoryMockRateForExpectation{mock: mmRateFor.mock}
	}
	mmRateFor.defaultExpectation.results = &RateRepositoryMockRateForResults{f1, err}
	mmRateFor.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRateFor.mock
}

// Set uses given function f to mock the RateRepository.RateFor method
func (mmRateFor *mRateRepositoryMockRateFor) Set(f func(ctx context.Context, status string) (f1 float64, err error)) *RateRepositoryMock {
	if mmRateFor.defaultExpectation != nil {
		mmRateFor.mock.t.Fatalf("Default expectation is already set for the RateRepository.RateFor method")
	}

	if len(mmRateFor.expectations) > 0 {
		mmRateFor.mock.t.Fatalf("Some expectations are already set for the RateRepository.RateFor method")
	}

	mmRateFor.mock.funcRateFor = f
	mmRateFor.mock.funcRateForOrigin = minimock.CallerInfo(1)
	return mmRateFor.mock
}

// When sets expectation for the RateRepository.RateFor which will trigger the result defined by the following
// Then helper
func (mmRateFor *mRateRepositoryMockRateFor) When(ctx context.Context, status string) *RateRepositoryMockRateForExpectation {
	if mmRateFor.mock.funcRateFor != nil {
		mmRateFor.mock.t.Fatalf("RateRepositoryMock.RateFor mock is already set by Set")
	}

	expectation := &RateRepositoryMockRateForExpectation{
		mock:               mmRateFor.mock,
		params:             &RateRepositoryMockRateForParams{ctx, status},
		expectationOrigins: RateRepositoryMockRateForExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRateFor.expectations = append(mmRateFor.expectations, expectation)
	return expectation
}

// Then sets up RateRepository.RateFor return parameters for the expectation previously defined by the When method
func (e *RateRepositoryMockRateForExpectation) Then(f1 float64, err error) *RateRepositoryMock {
	e.results = &RateRepositoryMockRateForResults{f1, err}
	return e.mock
}

// Times sets number of times RateRepository.RateFor should be invoked
func (mmRateFor *mRateRepositoryMockRateFor) Times(n uint64) *mRateRepositoryMockRateFor {
	if n == 0 {
		mmRateFor.mock.t.Fatalf("Times of RateRepositoryMock.RateFor mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRateFor.expectedInvocations, n)
	mmRateFor.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRateFor
}

func (mmRateFor *mRateRepositoryMockRateFor) invocationsDone() bool {
	if len(mmRateFor.expectations) == 0 && mmRateFor.defaultExpectation == nil && mmRateFor.mock.funcRateFor == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRateFor.mock.afterRateForCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRateFor.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// RateFor implements RateRepository
func (mmRateFor *RateRepositoryMock) RateFor(ctx context.Context, status string) (f1 float64, err error) {
	mm_atomic.AddUint64(&mmRateFor.beforeRateForCounter, 1)
	defer mm_atomic.AddUint64(&mmRateFor.afterRateForCounter, 1)

	mmRateFor.t.Helper()

	if mmRateFor.inspectFuncRateFor != nil {
		mmRateFor.inspectFuncRateFor(ctx, status)
	}

	mm_params := RateRepositoryMockRateForParams{ctx, status}

	// Record call args
	mmRateFor.RateForMock.mutex.Lock()
	mmRateFor.RateForMock.callArgs = append(mmRateFor.RateForMock.callArgs, &mm_params)
	mmRateFor.RateForMock.mutex.Unlock()

	for _, e := range mmRateFor.RateForMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.f1, e.results.err
		}
	}

	if mmRateFor.RateForMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRateFor.RateForMock.defaultExpectation.Counter, 1)
		mm_want := mmRateFor.RateForMock.defaultExpectation.params
		mm_want_ptrs := mmRateFor.RateForMock.defaultExpectation.paramPtrs

		mm_got := RateRepositoryMockRateForParams{ctx, status}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmRateFor.t.Errorf("RateRepositoryMock.RateFor got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRateFor.RateForMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.status != nil && !minimock.Equal(*mm_want_ptrs.status, mm_got.status) {
				mmRateFor.t.Errorf("RateRepositoryMock.RateFor got unexpected parameter status, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRateFor.RateForMock.defaultExpectation.expectationOrigins.originStatus, *mm_want_ptrs.status, mm_got.status, minimock.Diff(*mm_want_ptrs.status, mm_got.status))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRateFor.t.Errorf("RateRepositoryMock.RateFor got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRateFor.RateForMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRateFor.RateForMock.defaultExpectation.results
		if mm_results == nil {
			mmRateFor.t.Fatal("No results are set for the RateRepositoryMock.RateFor")
		}
		return (*mm_results).f1, (*mm_results).err
	}
	if mmRateFor.funcRateFor != nil {
		return mmRateFor.funcRateFor(ctx, status)
	}
	mmRateFor.t.Fatalf("Unexpected call to RateRepositoryMock.RateFor. %v %v", ctx, status)
	return
}

// RateForAfterCounter returns a count of finished RateRepositoryMock.RateFor invocations
func (mmRateFor *RateRepositoryMock) RateForAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRateFor.afterRateForCounter)
}

// RateForBeforeCounter returns a count of RateRepositoryMock.RateFor invocations
func (mmRateFor *RateRepositoryMock) RateForBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRateFor.beforeRateForCounter)
}

// Calls returns a list of arguments used in each call to RateRepositoryMock.RateFor.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRateFor *mRateRepositoryMockRateFor) Calls() []*RateRepositoryMockRateForParams {
	mmRateFor.mutex.RLock()

	argCopy := make([]*RateRepositoryMockRateForParams, len(mmRateFor.callArgs))
	copy(argCopy, mmRateFor.callArgs)

	mmRateFor.mutex.RUnlock()

	return argCopy
}

// MinimockRateForDone returns true if the count of the RateFor invocations corresponds
// the number of defined expectations
func (m *RateRepositoryMock) MinimockRateForDone() bool {
	if m.RateForMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RateForMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RateForMock.invocationsDone()
}

// MinimockRateForInspect logs each unmet expectation
func (m *RateRepositoryMock) MinimockRateForInspect() {
	for _, e := range m.RateForMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RateRepositoryMock.RateFor at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRateForCounter := mm_atomic.LoadUint64(&m.afterRateForCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RateForMock.defaultExpectation != nil && afterRateForCounter < 1 {
		if m.RateForMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RateRepositoryMock.RateFor at\n%s", m.RateForMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RateRepositoryMock.RateFor at\n%s with params: %#v", m.RateForMock.defaultExpectation.expectationOrigins.origin, *m.RateForMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRateFor != nil && afterRateForCounter < 1 {
		m.t.Errorf("Expected call to RateRepositoryMock.RateFor at\n%s", m.funcRateForOrigin)
	}

	if !m.RateForMock.invocationsDone() && afterRateForCounter > 0 {
		m.t.Errorf("Expected %d calls to RateRepositoryMock.RateFor at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RateForMock.expectedInvocations), m.RateForMock.expectedInvocationsOrigin, afterRateForCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RateRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockRateForInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RateRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RateRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockRateForDone()
}
