// Code generated by http://github.com/gojuno/minimock (v3.4.0). DO NOT EDIT.

package shop

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// UserRepositoryMock implements UserRepository
type UserRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcByID          func(ctx context.Context, id string) (u1 User, err error)
	funcByIDOrigin    string
	inspectFuncByID   func(ctx context.Context, id string)
	afterByIDCounter  uint64
	beforeByIDCounter uint64
	ByIDMock          mUserRepositoryMockByID
}

// NewUserRepositoryMock returns a mock for UserRepository
func NewUserRepositoryMock(t minimock.Tester) *UserRepositoryMock {
	m := &UserRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ByIDMock = mUserRepositoryMockByID{mock: m}
	m.ByIDMock.callArgs = []*UserRepositoryMockByIDParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUserRepositoryMockByID struct {
	optional           bool
	mock               *UserRepositoryMock
	defaultExpectation *UserRepositoryMockByIDExpectation
	expectations       []*UserRepositoryMockByIDExpectation

	callArgs []*UserRepositoryMockByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserRepositoryMockByIDExpectation specifies expectation struct of the UserRepository.ByID
type UserRepositoryMockByIDExpectation struct {
	mock               *UserRepositoryMock
	params             *UserRepositoryMockByIDParams
	paramPtrs          *UserRepositoryMockByIDParamPtrs
	expectationOrigins UserRepositoryMockByIDExpectationOrigins
	results            *UserRepositoryMockByIDResults
	returnOrigin       string
	Counter            uint64
}

// UserRepositoryMockByIDParams contains parameters of the UserRepository.ByID
type UserRepositoryMockByIDParams struct {
	ctx context.Context
	id  string
}

// UserRepositoryMockByIDParamPtrs contains pointers to parameters of the UserRepository.ByID
type UserRepositoryMockByIDParamPtrs struct {
	ctx *context.Context
	id  *string
}

// UserRepositoryMockByIDResults contains results of the UserRepository.ByID
type UserRepositoryMockByIDResults struct {
	u1  User
	err error
}

// UserRepositoryMockByIDOrigins contains origins of expectations of the UserRepository.ByID
type UserRepositoryMockByIDExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmByID *mUserRepositoryMockByID) Optional() *mUserRepositoryMockByID {
	mmByID.optional = true
	return mmByID
}

// Expect sets up expected params for UserRepository.ByID
func (mmByID *mUserRepositoryMockByID) Expect(ctx context.Context, id string) *mUserRepositoryMockByID {
	if mmByID.mock.funcByID != nil {
		mmByID.mock.t.Fatalf("UserRepositoryMock.ByID mock is already set by Set")
	}

	if mmByID.defaultExpectation == nil {
		mmByID.defaultExpectation = &UserRepositoryMockByIDExpectation{}
	}

	if mmByID.defaultExpectation.paramPtrs != nil {
		mmByID.mock.t.Fatalf("UserRepositoryMock.ByID mock is already set by ExpectParams functions")
	}

	mmByID.defaultExpectation.params = &UserRepositoryMockByIDParams{ctx, id}
	mmByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmByID.expectations {
		if minimock.Equal(e.params, mmByID.defaultExpectation.params) {
			mmByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmByID.defaultExpectation.params)
		}
	}

	return mmByID
}

// ExpectCtxParam1 sets up expected param ctx for UserRepository.ByID
func (mmByID *mUserRepositoryMockByID) ExpectCtxParam1(ctx context.Context) *mUserRepositoryMockByID {
	if mmByID.mock.funcByID != nil {
		mmByID.mock.t.Fatalf("UserRepositoryMock.ByID mock is already set by Set")
	}

	if mmByID.defaultExpectation == nil {
		mmByID.defaultExpectation = &UserRepositoryMockByIDExpectation{}
	}

	if mmByID.defaultExpectation.params != nil {
		mmByID.mock.t.Fatalf("UserRepositoryMock.ByID mock is already set by Expect")
	}

	if mmByID.defaultExpectation.paramPtrs == nil {
		mmByID.defaultExpectation.paramPtrs = &UserRepositoryMockByIDParamPtrs{}
	}
	mmByID.defaultExpectation.paramPtrs.ctx = &ctx
	mmByID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmByID
}

// ExpectIdParam2 sets up expected param id for UserRepository.ByID
func (mmByID *mUserRepositoryMockByID) ExpectIdParam2(id string) *mUserRepositoryMockByID {
	if mmByID.mock.funcByID != nil {
		mmByID.mock.t.Fatalf("UserRepositoryMock.ByID mock is already set by Set")
	}

	if mmByID.defaultExpectation == nil {
		mmByID.defaultExpectation = &UserRepositoryMockByIDExpectation{}
	}

	if mmByID.defaultExpectation.params != nil {
		mmByID.mock.t.Fatalf("UserRepositoryMock.ByID mock is already set by Expect")
	}

	if mmByID.defaultExpectation.paramPtrs == nil {
		mmByID.defaultExpectation.paramPtrs = &UserRepositoryMockByIDParamPtrs{}
	}
	mmByID.defaultExpectation.paramPtrs.id = &id
	mmByID.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmByID
}

// Inspect accepts an inspector function that has same arguments as the UserRepository.ByID
func (mmByID *mUserRepositoryMockByID) Inspect(f func(ctx context.Context, id string)) *mUserRepositoryMockByID {
	if mmByID.mock.inspectFuncByID != nil {
		mmByID.mock.t.Fatalf("Inspect function is already set for UserRepositoryMock.ByID")
	}

	mmByID.mock.inspectFuncByID = f

	return mmByID
}

// Return sets up results that will be returned by UserRepository.ByID
func (mmByID *mUserRepositoryMockByID) Return(u1 User, err error) *UserRepositoryMock {
	if mmByID.mock.funcByID != nil {
		mmByID.mock.t.Fatalf("UserRepositoryMock.ByID mock is already set by Set")
	}

	if mmByID.defaultExpectation == nil {
		mmByID.defaultExpectation = &UserRepositoryMockByIDExpectation{mock: mmByID.mock}
	}
	mmByID.defaultExpectation.results = &UserRepositoryMockByIDResults{u1, err}
	mmByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmByID.mock
}

// Set uses given function f to mock the UserRepository.ByID method
func (mmByID *mUserRepositoryMockByID) Set(f func(ctx context.Context, id string) (u1 User, err error)) *UserRepositoryMock {
	if mmByID.defaultExpectation != nil {
		mmByID.mock.t.Fatalf("Default expectation is already set for the UserRepository.ByID method")
	}

	if len(mmByID.expectations) > 0 {
		mmByID.mock.t.Fatalf("Some expectations are already set for the UserRepository.ByID method")
	}

	mmByID.mock.funcByID = f
	mmByID.mock.funcByIDOrigin = minimock.CallerInfo(1)
	return mmByID.mock
}

// When sets expectation for the UserRepository.ByID which will trigger the result defined by the following
// Then helper
func (mmByID *mUserRepositoryMockByID) When(ctx context.Context, id string) *UserRepositoryMockByIDExpectation {
	if mmByID.mock.funcByID != nil {
		mmByID.mock.t.Fatalf("UserRepositoryMock.ByID mock is already set by Set")
	}

	expectation := &UserRepositoryMockByIDExpectation{
		mock:               mmByID.mock,
		params:             &UserRepositoryMockByIDParams{ctx, id},
		expectationOrigins: UserRepositoryMockByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmByID.expectations = append(mmByID.expectations, expectation)
	return expectation
}

// Then sets up UserRepository.ByID return parameters for the expectation previously defined by the When method
func (e *UserRepositoryMockByIDExpectation) Then(u1 User, err error) *UserRepositoryMock {
	e.results = &UserRepositoryMockByIDResults{u1, err}
	return e.mock
}

// Times sets number of times UserRepository.ByID should be invoked
func (mmByID *mUserRepositoryMockByID) Times(n uint64) *mUserRepositoryMockByID {
	if n == 0 {
		mmByID.mock.t.Fatalf("Times of UserRepositoryMock.ByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmByID.expectedInvocations, n)
	mmByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmByID
}

func (mmByID *mUserRepositoryMockByID) invocationsDone() bool {
	if len(mmByID.expectations) == 0 && mmByID.defaultExpectation == nil && mmByID.mock.funcByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmByID.mock.afterByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ByID implements UserRepository
func (mmByID *UserRepositoryMock) ByID(ctx context.Context, id string) (u1 User, err error) {
	mm_atomic.AddUint64(&mmByID.beforeByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmByID.afterByIDCounter, 1)

	mmByID.t.Helper()

	if mmByID.inspectFuncByID != nil {
		mmByID.inspectFuncByID(ctx, id)
	}

	mm_params := UserRepositoryMockByIDParams{ctx, id}

	// Record call args
	mmByID.ByIDMock.mutex.Lock()
	mmByID.ByIDMock.callArgs = append(mmByID.ByIDMock.callArgs, &mm_params)
	mmByID.ByIDMock.mutex.Unlock()

	for _, e := range mmByID.ByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.u1, e.results.err
		}
	}

	if mmByID.ByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmByID.ByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmByID.ByIDMock.defaultExpectation.params
		mm_want_ptrs := mmByID.ByIDMock.defaultExpectation.paramPtrs

		mm_got := UserRepositoryMockByIDParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmByID.t.Errorf("UserRepositoryMock.ByID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmByID.ByIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmByID.t.Errorf("UserRepositoryMock.ByID got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmByID.ByIDMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmByID.t.Errorf("UserRepositoryMock.ByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmByID.ByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmByID.ByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmByID.t.Fatal("No results are set for the UserRepositoryMock.ByID")
		}
		return (*mm_results).u1, (*mm_results).err
	}
	if mmByID.funcByID != nil {
		return mmByID.funcByID(ctx, id)
	}
	mmByID.t.Fatalf("Unexpected call to UserRepositoryMock.ByID. %v %v", ctx, id)
	return
}

// ByIDAfterCounter returns a count of finished UserRepositoryMock.ByID invocations
func (mmByID *UserRepositoryMock) ByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmByID.afterByIDCounter)
}

// ByIDBeforeCounter returns a count of UserRepositoryMock.ByID invocations
func (mmByID *UserRepositoryMock) ByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmByID.beforeByIDCounter)
}

// Calls returns a list of arguments used in each call to UserRepositoryMock.ByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmByID *mUserRepositoryMockByID) Calls() []*UserRepositoryMockByIDParams {
	mmByID.mutex.RLock()

	argCopy := make([]*UserRepositoryMockByIDParams, len(mmByID.callArgs))
	copy(argCopy, mmByID.callArgs)

	mmByID.mutex.RUnlock()

	return argCopy
}

// MinimockByIDDone returns true if the count of the ByID invocations corresponds
// the number of defined expectations
func (m *UserRepositoryMock) MinimockByIDDone() bool {
	if m.ByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ByIDMock.invocationsDone()
}

// MinimockByIDInspect logs each unmet expectation
func (m *UserRepositoryMock) MinimockByIDInspect() {
	for _, e := range m.ByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserRepositoryMock.ByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterByIDCounter := mm_atomic.LoadUint64(&m.afterByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ByIDMock.defaultExpectation != nil && afterByIDCounter < 1 {
		if m.ByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserRepositoryMock.ByID at\n%s", m.ByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserRepositoryMock.ByID at\n%s with params: %#v", m.ByIDMock.defaultExpectation.expectationOrigins.origin, *m.ByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcByID != nil && afterByIDCounter < 1 {
		m.t.Errorf("Expected call to UserRepositoryMock.ByID at\n%s", m.funcByIDOrigin)
	}

	if !m.ByIDMock.invocationsDone() && afterByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to UserRepositoryMock.ByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ByIDMock.expectedInvocations), m.ByIDMock.expectedInvocationsOrigin, afterByIDCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UserRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockByIDInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UserRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UserRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockByIDDone()
}
