// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package shop

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// ByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) ByID(ctx context.Context, id string) (User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type MockUserRepository_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepository_Expecter) ByID(ctx interface{}, id interface{}) *MockUserRepository_ByID_Call {
	return &MockUserRepository_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *MockUserRepository_ByID_Call) Run(run func(ctx context.Context, id string)) *MockUserRepository_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_ByID_Call) Return(user User, err error) *MockUserRepository_ByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_ByID_Call) RunAndReturn(run func(ctx context.Context, id string) (User, error)) *MockUserRepository_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRateRepository creates a new instance of MockRateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRateRepository {
	mock := &MockRateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRateRepository is an autogenerated mock type for the RateRepository type
type MockRateRepository struct {
	mock.Mock
}

type MockRateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRateRepository) EXPECT() *MockRateRepository_Expecter {
	return &MockRateRepository_Expecter{mock: &_m.Mock}
}

// RateFor provides a mock function for the type MockRateRepository
func (_mock *MockRateRepository) RateFor(ctx context.Context, status string) (float64, error) {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for RateFor")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return returnFunc(ctx, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = returnFunc(ctx, status)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRateRepository_RateFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RateFor'
type MockRateRepository_RateFor_Call struct {
	*mock.Call
}

// RateFor is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
func (_e *MockRateRepository_Expecter) RateFor(ctx interface{}, status interface{}) *MockRateRepository_RateFor_Call {
	return &MockRateRepository_RateFor_Call{Call: _e.mock.On("RateFor", ctx, status)}
}

func (_c *MockRateRepository_RateFor_Call) Run(run func(ctx context.Context, status string)) *MockRateRepository_RateFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRateRepository_RateFor_Call) Return(f float64, err error) *MockRateRepository_RateFor_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MockRateRepository_RateFor_Call) RunAndReturn(run func(ctx context.Context, status string) (float64, error)) *MockRateRepository_RateFor_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAudit creates a new instance of MockAudit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAudit(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAudit {
	mock := &MockAudit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAudit is an autogenerated mock type for the Audit type
type MockAudit struct {
	mock.Mock
}

type MockAudit_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAudit) EXPECT() *MockAudit_Expecter {
	return &MockAudit_Expecter{mock: &_m.Mock}
}

// Record provides a mock function for the type MockAudit
func (_mock *MockAudit) Record(ctx context.Context, userID string, amount float64) error {
	ret := _mock.Called(ctx, userID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, float64) error); ok {
		r0 = returnFunc(ctx, userID, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAudit_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockAudit_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - amount float64
func (_e *MockAudit_Expecter) Record(ctx interface{}, userID interface{}, amount interface{}) *MockAudit_Record_Call {
	return &MockAudit_Record_Call{Call: _e.mock.On("Record", ctx, userID, amount)}
}

func (_c *MockAudit_Record_Call) Run(run func(ctx context.Context, userID string, amount float64)) *MockAudit_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAudit_Record_Call) Return(err error) *MockAudit_Record_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAudit_Record_Call) RunAndReturn(run func(ctx context.Context, userID string, amount float64) error) *MockAudit_Record_Call {
	_c.Call.Return(run)
	return _c
}
